### ISSUE TITLE
Handle errors

### ISSUE THREAD

**Issue by gaearon** [rt2zz/redux-persist-store#1]
Be careful with `localStorage`! The data might get corrupted or something, so `try`/`catch` is a good idea.
Worse, iOS in private mode will throw on every `.setItem` or `.getItem` call.

**Comment by rt2zz** [comment]
Added `try/catch`, thanks. 

I am still trying to figure out a decent api for persisting state. One function with 4 (mostly optional) arguments is clumsy. Also having to add a rehydrate action handler per reducer can be tedious and error prone.

**Comment by gaearon** [comment]
Why not rehydrate by providing the initial state? For example that's how [persistState](https://github.com/gaearon/redux-devtools/blob/master/src/persistState.js) works.

**Comment by rt2zz** [comment]
@gaearon a few things:
- support async storage api's (e.g. react-native)
- allow for performance optimizations in the future, perhaps web workers for parsing
- reducers can conditionally or partially rehydrate. E.G. a reducer might refuse data based on an expiry date.
- All of the other fluxy benefits, e.g. make debugging easy and explicit. If a rehydration is causing problems one can easily trace it back to the action.

I implemented pluggable storage last night in order to support react-native. New API:
```js
const config = {
  blacklist: ['someReducer'], 
  actionCreator:rehydrate,
  storage: AsyncStorage,
}
persistStore(store, config, () => {
  console.log('restored')
})
```

**Comment by ksairi** [comment]
@rt2zz how can I catch an error, i.e of no space in disk, while the persist action is happening in a react native app?
